/* ============================================================
   Borderless — seed data (ported from design_handoff/data.js)
   Phase 1: hard-coded. Phase 2 replaces this with Supabase reads.
   Today = 2026-06-10.
   ============================================================ */

import type {
  Event,
  CategoryMeta,
  Category,
  Tier,
  Reward,
  CoverKey,
} from "./types";

// ---- cover palettes (placeholder imagery) ----
export const covers: Record<CoverKey, [string, string, string]> = {
  matsuri: ["#8A3233", "#C4583B", "#E8A04A"],
  night: ["#2C2540", "#5B3B6B", "#A8476B"],
  tea: ["#5B6B4A", "#8AA36B", "#C9C58B"],
  river: ["#2E5C6E", "#4E8FA6", "#9FC9CE"],
  food: ["#7A3B2E", "#C06A3C", "#E6B25A"],
  lantern: ["#3A2230", "#8A3233", "#D98C4A"],
  sakura: ["#7A3050", "#C2657F", "#F2C2CE"],
  zen: ["#4A463E", "#7E7869", "#BDB39B"],
};

// ---- events (mix past + upcoming). Today = 2026-06-10 ----
export const events: Event[] = [
  {
    id: "e10",
    slug: "midsummer-yukata",
    cover: "matsuri",
    category: "cultural",
    title: { en: "Midsummer Yukata Night", jp: "真夏の浴衣ナイト" },
    date: "2026-06-13",
    time: "18:30",
    endTime: "22:00",
    venue: { en: "Kamogawa Riverbank, Sanjo", jp: "鴨川河川敷・三条" },
    area: { en: "Pontocho", jp: "先斗町" },
    price: 2500,
    capacity: 24,
    cost: 40000,
    status: "published",
    blurb: {
      en: "Wear a yukata, stroll the Kamogawa at dusk, and join us for street food and sparklers.",
      jp: "浴衣を着て、夕暮れの鴨川を散歩。屋台グルメと線香花火を楽しみましょう。",
    },
    desc: {
      en: "Summer in Kyoto begins on the river. Borrow or bring a yukata (we have a few spares + a quick-dressing helper on site), and meet us where the Kamogawa meets Sanjo bridge. We'll walk down to a quiet stretch of bank, lay out mats, and share kakigōri, yakitori, and cold drinks while the lanterns of Pontocho light up across the water. As night falls we hand out senkō hanabi — the delicate Japanese sparklers — and see whose flame lasts longest. All nationalities, all language levels welcome.",
      jp: "京都の夏は川から始まります。浴衣を着て（予備とお着付けヘルパーも用意しています）、三条大橋のたもとに集合。静かな河原にマットを敷き、かき氷・焼き鳥・冷たい飲み物を囲みながら、対岸の先斗町の灯りを眺めます。夜が更けたら線香花火を配り、誰の火が一番長く続くか競争。国籍も語学レベルも問いません。",
    },
    invited: 31,
    rsvp: 19,
    gallery: 0,
    lat: 35.009,
    lng: 135.772,
  },
  {
    id: "e11",
    slug: "ramen-crawl-shijo",
    cover: "food",
    category: "food",
    title: { en: "Hidden Ramen Crawl", jp: "隠れ家ラーメン巡り" },
    date: "2026-06-20",
    time: "19:00",
    endTime: "22:30",
    venue: { en: "Start: Karasuma Station Exit 5", jp: "集合：烏丸駅5番出口" },
    area: { en: "Shijō–Karasuma", jp: "四条烏丸" },
    price: 3800,
    capacity: 14,
    cost: 28000,
    status: "published",
    blurb: {
      en: "Three counter-only ramen shops most tourists never find, one unforgettable night.",
      jp: "観光客が知らないカウンターだけのラーメン店を3軒巡る、忘れられない夜。",
    },
    desc: {
      en: "We've made friends with three tiny ramen masters tucked down Kyoto's back alleys — the kind of places with six seats, no English menu, and a line of locals. Tonight we go behind the noren. Small group (14 max) so we actually fit. Price covers a half-portion at each shop plus a first drink; come hungry and curious.",
      jp: "京都の路地裏にある小さなラーメン店3軒の店主と仲良くなりました。6席だけ、英語メニューなし、地元客が並ぶようなお店です。今夜は暖簾の奥へ。少人数（最大14名）でちょうど収まります。料金は各店ハーフサイズ＋最初の1杯込み。空腹と好奇心を持って来てください。",
    },
    invited: 22,
    rsvp: 14,
    gallery: 0,
    lat: 35.0036,
    lng: 135.759,
  },
  {
    id: "e12",
    slug: "tea-zazen-morning",
    cover: "tea",
    category: "workshop",
    title: { en: "Temple Zazen & Matcha", jp: "坐禅と抹茶の朝" },
    date: "2026-06-27",
    time: "08:00",
    endTime: "10:30",
    venue: { en: "Shōkoku-ji Sub-temple", jp: "相国寺塔頭" },
    area: { en: "Imadegawa", jp: "今出川" },
    price: 3200,
    capacity: 18,
    cost: 30000,
    status: "published",
    blurb: {
      en: "A guided morning zazen sitting followed by whisking your own bowl of matcha.",
      jp: "朝の坐禅体験のあと、自分でお抹茶を点てます。",
    },
    desc: {
      en: "Start the day in stillness. A monk guides a 40-minute zazen sitting (cushions and instruction provided, no experience needed), followed by a short talk and a tea session where you whisk your own bowl of matcha with seasonal wagashi. Quiet, grounding, and a beautiful way to see a working temple from the inside.",
      jp: "静けさから一日を始めましょう。僧侶の指導で40分の坐禅（座布団・説明あり、経験不要）、その後の法話と、季節の和菓子とともに自分でお抹茶を点てる茶席。静かで心が整う、生きたお寺を内側から見る素敵な体験です。",
    },
    invited: 26,
    rsvp: 11,
    gallery: 0,
    lat: 35.0297,
    lng: 135.761,
  },
  // ---- past events ----
  {
    id: "e09",
    slug: "language-exchange-may",
    cover: "lantern",
    category: "language",
    title: { en: "Language Exchange × Izakaya", jp: "言語交換×居酒屋" },
    date: "2026-06-06",
    time: "19:00",
    endTime: "22:00",
    venue: { en: "Izakaya Den, Kiyamachi", jp: "居酒屋 田、木屋町" },
    area: { en: "Kiyamachi", jp: "木屋町" },
    price: 2800,
    capacity: 30,
    cost: 50000,
    status: "completed",
    blurb: {
      en: "Rotating tables, five languages, endless small plates.",
      jp: "テーブルを回って5言語、小皿料理は無限。",
    },
    desc: {
      en: "Our flagship monthly mixer. Rotating tables every 20 minutes, language stickers, and a private izakaya floor.",
      jp: "毎月恒例の看板イベント。20分ごとにテーブル交代、言語ステッカー、貸切の居酒屋フロア。",
    },
    invited: 38,
    attended: 29,
    gallery: 14,
    lat: 35.004,
    lng: 135.77,
  },
  {
    id: "e08",
    slug: "arashiyama-hike",
    cover: "river",
    category: "outdoor",
    title: { en: "Arashiyama Bamboo Hike", jp: "嵐山・竹林ハイク" },
    date: "2026-05-30",
    time: "09:30",
    endTime: "15:00",
    venue: { en: "Saga-Arashiyama Station", jp: "嵯峨嵐山駅" },
    area: { en: "Arashiyama", jp: "嵐山" },
    price: 2000,
    capacity: 22,
    cost: 25000,
    status: "completed",
    blurb: {
      en: "Bamboo grove at opening hour, monkey park, riverside lunch.",
      jp: "開門直後の竹林、モンキーパーク、川辺のランチ。",
    },
    desc: {
      en: "Beat the crowds to the bamboo grove, climb to the monkey park, and picnic by the Hozugawa.",
      jp: "人混みを避けて竹林へ、モンキーパークに登り、保津川のほとりでピクニック。",
    },
    invited: 27,
    attended: 21,
    gallery: 22,
    lat: 35.0094,
    lng: 135.667,
  },
  {
    id: "e07",
    slug: "rooftop-djs",
    cover: "night",
    category: "nightlife",
    title: { en: "Rooftop Sundown Sessions", jp: "ルーフトップ・サンダウン" },
    date: "2026-05-23",
    time: "17:00",
    endTime: "23:00",
    venue: { en: "Bar Above, Kawaramachi", jp: "Bar Above、河原町" },
    area: { en: "Kawaramachi", jp: "河原町" },
    price: 3500,
    capacity: 40,
    cost: 98000,
    status: "completed",
    blurb: {
      en: "Local DJs, city skyline, one welcome cocktail.",
      jp: "地元DJ、街の夜景、ウェルカムカクテル付き。",
    },
    desc: {
      en: "Our biggest night yet — three local DJs, a rooftop over Kawaramachi, and the whole circle dancing.",
      jp: "過去最大の夜——地元DJ3組、河原町を見下ろすルーフトップ、サークル全員でダンス。",
    },
    invited: 52,
    attended: 44,
    gallery: 38,
    lat: 35.0048,
    lng: 135.768,
  },
  {
    id: "e06",
    slug: "pottery-workshop",
    cover: "zen",
    category: "workshop",
    title: { en: "Kiyomizu Pottery Workshop", jp: "清水焼の陶芸教室" },
    date: "2026-05-16",
    time: "13:00",
    endTime: "16:00",
    venue: { en: "Tōki Studio, Gojō-zaka", jp: "陶器スタジオ、五条坂" },
    area: { en: "Gojō-zaka", jp: "五条坂" },
    price: 4200,
    capacity: 12,
    cost: 35000,
    status: "completed",
    blurb: {
      en: "Throw your own cup on the wheel, fired and mailed to you.",
      jp: "ろくろで自分の器を作り、焼成後に郵送します。",
    },
    desc: {
      en: "Hands-on wheel-throwing with a Kiyomizu-ware potter. Your piece is glazed, fired, and shipped within a month.",
      jp: "清水焼の陶芸家とろくろ体験。作品は釉薬をかけて焼成し、1か月以内に郵送します。",
    },
    invited: 18,
    attended: 12,
    gallery: 16,
    lat: 34.996,
    lng: 135.781,
  },
  {
    id: "e05",
    slug: "sakura-hanami",
    cover: "sakura",
    category: "cultural",
    title: { en: "Late Sakura Hanami Picnic", jp: "遅咲き桜の花見" },
    date: "2026-05-09",
    time: "11:00",
    endTime: "16:00",
    venue: { en: "Kyoto Botanical Gardens", jp: "京都府立植物園" },
    area: { en: "Kitayama", jp: "北山" },
    price: 1800,
    capacity: 35,
    cost: 36000,
    status: "completed",
    blurb: {
      en: "Blankets, bentō, and the season's last blossoms.",
      jp: "レジャーシート、お弁当、今季最後の桜。",
    },
    desc: {
      en: "The botanical gardens hold late-blooming sakura long after the city's have fallen. Bring a blanket; we bring the bentō.",
      jp: "植物園では街中の桜が散った後も遅咲きの桜が楽しめます。シートをご持参ください。お弁当はこちらで用意します。",
    },
    invited: 44,
    attended: 33,
    gallery: 41,
    lat: 35.049,
    lng: 135.764,
  },
];

// ---- categories ----
export const categories: Record<Category, CategoryMeta> = {
  cultural: { en: "Cultural", jp: "文化", color: "#8A3233" },
  food: { en: "Food", jp: "グルメ", color: "#C06A3C" },
  nightlife: { en: "Nightlife", jp: "ナイト", color: "#5B3B6B" },
  outdoor: { en: "Outdoor", jp: "アウトドア", color: "#4E8FA6" },
  workshop: { en: "Workshop", jp: "ワークショップ", color: "#5B6B4A" },
  language: { en: "Language", jp: "言語交換", color: "#B4893C" },
};

// ---- tiers ----
export const tiers: Tier[] = [
  { key: "Guest", min: 0, jp: "ゲスト", color: "#9A8B7D" },
  { key: "Regular", min: 5, jp: "レギュラー", color: "#B4893C" },
  { key: "Insider", min: 15, jp: "インサイダー", color: "#8A3233" },
];

// ---- rewards ----
export const rewards: Reward[] = [
  { id: "r1", cost: 10, title: { en: "Free entry to any paid event", jp: "有料イベント1回無料" }, tag: "popular" },
  { id: "r2", cost: 6, title: { en: "Bring a friend for free", jp: "友達1名を無料招待" } },
  { id: "r3", cost: 8, title: { en: "Reserved seat + welcome drink", jp: "席予約＋ウェルカムドリンク" } },
  { id: "r4", cost: 20, title: { en: "Borderless yukata or tote", jp: "ボーダレス浴衣またはトート" }, tag: "limited" },
];
